# Set Win key as Modifier
set $mod Mod4

# ProtonVPN
exec --no-startup-id protonvpn-app

# Font for window titles. Will also be used by the bar.
font pango:monospace 8

# start a terminal
bindsym $mod+Return exec foot --font 'Monospace'

# wlsunset

exec_always wlsunset -t 4200 -T 6500 -S 6:30 -s 18:30 -g 1.2

# front panel buttons

bindcode 147 exec --no-startup-id wvkbd-mobintl -L 180
bindsym Control+Escape exec pkill wvkbd-mobintl
bindcode 159 exec --no-startup-id python ~/.config/scripts/cf-19-rotate.py
bindcode 160 exec systemctl suspend

# Bar

bar {
        status_command i3status -c ~/.config/sway/panasonic-cf19.status
}

include ~/.config/sway/main.conf
